---
# tasks file for apigee-opdk-setup-bootstrap-archive-installer
- name: Configure local repository
  shell: "bash {{ archive_folder }}/repos/{{ bootstrap_filename }} apigeeprotocol='file://' apigeerepobasepath={{ archive_folder }}/repos JAVA_FIX=C"

- name: Install apigee setup service
  shell: '{{ apigee_service }} apigee-setup install'

